#!/usr/bin/env sh

set -e
set -x

nix flake check --print-build-logs
coverage run -m unittest discover
coverage html
nix build
nix-instantiate -E --strict "$(result/bin/nix-prefetch-github seppeljordan nix-prefetch-github --nix)"
nix-instantiate -E --strict "$(result/bin/nix-prefetch-github-latest-release seppeljordan nix-prefetch-github --nix)"
nix-instantiate -E --strict "$(result/bin/nix-prefetch-github-directory --nix)"
nix-instantiate -E --strict "$(result/bin/nix-prefetch-github seppeljordan nix-prefetch-github --nix --leave-dot-git)"
