import textwrap
from typing import Any

class TextWrapper(textwrap.TextWrapper):
    initial_indent: Any = ...
    subsequent_indent: Any = ...
    def extra_indent(self, indent: Any) -> None: ...
    def indent_only(self, text: Any): ...
