from typing import Any, Optional

def get_current_context(silent: bool = ...): ...
def push_context(ctx: Any) -> None: ...
def pop_context() -> None: ...
def resolve_color_default(color: Optional[Any] = ...): ...
